services:
  server:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=${DB_PASSWORD}
    restart: always
    networks:
      - forgejo
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${WEB_PORT:-3000}:3000"
      - "${SSH_PORT:-222}:22"
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_DB=forgejo
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - forgejo
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    forgejo:
    postgres:

networks:
  forgejo:
    external: false